import React from "react"
import styled from "styled-components"

const TitleBarContainer = styled.div`
    padding: ${props => props.theme.space[0]};
    background-color: ${props => props.theme.colorPalette.background2};
    color: ${props => props.theme.colorPalette.text2};
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
`

const TitleBarTitle = styled.h1`
    font-size: ${props => props.theme.fontSizes[0]};
}
`
const TitleBarSubtitle = styled.h4`
    font-size: ${props => props.theme.fontSizes[1]};
}
`
export default function TitleBar() {
    return (
        <TitleBarContainer>
            <TitleBarTitle>GPT MCQ</TitleBarTitle>
            <TitleBarSubtitle>MCQ questions generated by AI</TitleBarSubtitle>
        </TitleBarContainer>
    );
    }