import Link from "next/link"
import React from "react"
import styled from "styled-components"

const TitleBarContainer = styled.div`
    padding: ${props => props.theme.space[2]};
    background-color: ${props => props.theme.colorPalette.background2};
    color: ${props => props.theme.colorPalette.text2};
    display: flex;
    flex-direction: row;
    align-items: center;
    justify-content: space-between;
`

const TitleBarTitle = styled.div`
    font-size: ${props => props.theme.fontSizes[0]};
    color: ${props => props.theme.colorPalette.text};
    cursor: pointer;
}
`
const TitleBarSubtitle = styled.div`
    font-size: ${props => props.theme.fontSizes[1]};
}
`
export default function TitleBar() {
    return (
        <TitleBarContainer>
            <Link href="/" style={{ textDecoration: 'none'}}>
            <TitleBarTitle>GPT MCQ</TitleBarTitle>
            </Link>
            <TitleBarSubtitle>Multiple-choice questions generated by AI</TitleBarSubtitle>
        </TitleBarContainer>
    );
    }